name: 'Terraform PR Commenter by Juan-VG'
description: 'Adds opinionated comments to a PR from Terraform fmt/init/plan output'
author: 'Juan-VG'
branding:
  icon: 'git-pull-request'
  color: 'green'
inputs:
  commenter_type:
    description: 'The type of comment. Options: [fmt, init, plan]'
    required: true
  commenter_input_file:
    description: 'The file containing the comment to post from a previous step output'
    required: true
  commenter_exitcode:
    description: 'The exit code from a previous step output'
    required: true
  commenter_job_name:
    description: '(Optional) The job name where Terraform is run in. Set this to make the logs link more accurate'
    required: false
  commenter_step_name:
    description: '(Optional) The step name where Terraform is run in. Set this to make the logs link more accurate'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.commenter_type }}
    - ${{ inputs.commenter_input_file }}
    - ${{ inputs.commenter_exitcode }}
    - ${{ inputs.commenter_job_name }}
    - ${{ inputs.commenter_step_name }}
